version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: compose/local/Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ../../:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: "unless-stopped"
    depends_on:
      - db
  db:
    image: "mysql:latest"
    volumes:
      - ../../mysql-data:/var/lib/mysql
    restart: "always"
    env_file:
      - ./.env
    ports:
      - "3306:3306"
